name: example-environment
channels:
  - conda-forge
dependencies:
  - numpy
  - psutil
  - toolz
  - pathlib
  - matplotlib
  - dill
  - pandas
  - scipy
  - partd
  - bokeh
  - dask
  - xarray
  - datetime